config/routes.rb
Rails.application.routes.draw do
 
  resources :questions
  resources :quizzes
  get 'home/index'
  root :to => "home#index"
  post "questions/:id", to: "questions#check_answer"
  get 'quizzes/:id/reset', to: "quizzes#reset", as: "reset"
  get "quizzes/:id/build", to: "quizzes#build", as: "build_quiz"
  get "quizzes/:id/complete", to: "quizzes#complete", as: "complete"
  get "quizzes/:id/session_maker", to: "quizzes#session_maker", as: "session_maker"
  get "quizzes/:id/add_question_to_quiz", to: "quizzes#add_question_to_quiz", as: "add_question_to_quiz"
  post "quizzes/:id/session_maker", to: "quizzes#handle_answer"
  get "random", to: "quizzes#pick_random_quiz"
end

app/models/question.rb
class Question < ApplicationRecord
    
    has_many :quizzes_questions
    has_many :quizzes, through: :quizzes_question
    validates_presence_of :title
    validates_presence_of :answer

    after_create_commit { broadcast_prepend_to :questions}
    def check_answer(attempt)
       
        if attempt == self.answer
            true 
        else
            false
        end
    end

    def mark_as_answered
        self.answered = true
        self.save
    end

    def mark_as_unanswered
        self.answered = false
        self.save
    end

    def correct_answer
        self.answer
    end

   
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: %i[ show edit update destroy check_answer]
  before_action :set_up_first_and_next_question, only: %i[show check_answer beginning_of_quiz]

  # GET /questions or /questions.json
  def index
    @questions = Question.all
    @question = Question.new
  end

  # GET /questions/1 or /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions or /questions.json
  def create
    @quiz = Quiz.find(question_params[:quiz_id])
    @question = Question.new(question_params)
    
    respond_to do |format|
      if @question.save
        format.html { redirect_to build_quiz_path(@quiz) }
        format.json { render :show, status: :created, location: @question }
      else
    
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@question, parital: "questions/form", locals: { question: @question})}
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1 or /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: "Question was successfully updated." }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1 or /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url, notice: "Question was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def check_answer
   
    attempt = params[:question][:attempt]
    correct_answer = @display_question.correct_answer

    if @display_question.check_answer(attempt) == true
     
      attempted_answer.correct_answer = true
      @display_question.mark_as_answered
      respond_to do |format|
        if @queued_question 
          attempted_answer.save

          format.html { redirect_to start_path, notice: "Correct!" }
          format.json { head :no_content }
          
         
        else
          attempted_answer.save

          format.html { redirect_to complete_path, notice: "Correct!" }
          format.json { head :no_content }
        end
      end
    else
      attempted_answer.correct_answer = false
      attempted_answer.save

      respond_to do |format|
        format.html { redirect_to start_path, notice: "Question was answered incorrectly." }
        format.json { head :no_content }
      end
    end
  end

  def end_of_quiz
  end

  def beginning_of_quiz
  end

  def reset
    @questions = Question.all
    @questions.each do |question| 
      question.mark_as_unanswered
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    def set_up_first_and_next_question
      @display_question = Question.where(answered: false).first
      @queued_question = Question.where(answered: false).second
    end

    # Only allow a list of trusted parameters through.
    def question_params
      params.require(:question).permit(:title, :answer, :attempt, :quiz_id)
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
<%= form_with(model: question, local: true) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class = "left-text">
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>

    <div class="field">
      <%= form.label :answer %>
      <%= form.text_field :answer %>
    </div>

    <div class="field">
      <%= form.label :quiz_id, "Quiz ID" %>
      <%= form.text_field :quiz_id %>
    </div>

    <div class="actions">
      <%= form.submit %>
    </div>
  </div>
<% end %>

app/views/questions/_question.html.erb
<div id="<%= dom_id question %>">
<div class = "left-text">
  <tr>

    <%= question.title %>
  
  </tr>
  </div>

</div>

app/views/questions/beginning_of_quiz.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @display_question.title  if @display_question.present? %>
</p>

<% if @display_question.present? %>
  <%= render 'answer_form', question: @display_question %>
<% else %>
  <%= render "all_questions_answered" %>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing Question</h1>

<%= render 'form', question: @question %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<%= turbo_stream_from :questions %>


<div class="split left">
  <div class="centered">
  <h1>Add a Question</h1>
  <%= turbo_frame_tag :questions_form do %>
    <%= render 'questions/form', question: @question %>
  <% end %>
  </div>
</div>

<div class="split right">
  <div class="centered">
  <h1>Questions</h1>
    
    <%= turbo_frame_tag :questions do %>
      <%= render @questions %>
    <% end %>
  
  </div>
</div>

app/views/questions/new.html.erb
<h1>Add a new Question</h1>

<%= render 'form', question: @question %>

app/views/questions/reset.html.erb
<h1>Reset the quiz</h1>
<p>Click here to get started: </p>
<%= link_to "Let's go", start_path %> 

app/views/questions/show.html.erb
<%= @display_question.title %>

<%= form_with(model: @display_question, local: true, method: :post) do |form| %>
  <%= form.text_field :your_answer %>
  <%= form.submit "Check Answer" %>
<% end %>