config/routes.rb
Rails.application.routes.draw do
 
  resources :questions
  resources :quizzes
  get 'home/index'
  root :to => "home#index"
  post "questions/:id", to: "questions#check_answer"
  get 'quizzes/:id/reset', to: "quizzes#reset", as: "reset"
  get "quizzes/:id/build", to: "quizzes#build", as: "build_quiz"
  get "quizzes/:id/complete", to: "quizzes#complete", as: "complete"
  get "quizzes/:id/session_maker", to: "quizzes#session_maker", as: "session_maker"
  get "quizzes/:id/add_question_to_quiz", to: "quizzes#add_question_to_quiz", as: "add_question_to_quiz"
  post "quizzes/:id/session_maker", to: "quizzes#handle_answer"
  get "random", to: "quizzes#pick_random_quiz"
end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
  before_action :setup_quiz, only: %i[session_maker handle_answer show edit update destroy build complete]

  # GET /quizzes or /quizzes.json
  def index
    @quizzes = Quiz.all.order(created_at: :desc)
    @quiz = Quiz.new
  end

  # GET /quizzes/1 or /quizzes/1.json
  def show
    @quiz_questions = Question.all
    # @quiz_questions = @quiz.questions.all
    # byebug # are any quiz questions false?  
    if @quiz_questions.present?
      intro_new_quiz(@quiz_questions)
      @display_question = @quiz_questions.where(answered: false).first
    else
      redirect_to build_quiz_path
    end
    
  end

  # GET /quizzes/new
  def new
    @quiz = Quiz.new
  end

  # GET /quizzes/1/edit
  def edit
  
  end

  # POST /quizzes or /quizzes.json
  def create
    @quiz = Quiz.new(quiz_params)

    respond_to do |format|
      if @quiz.save
        format.html { redirect_to quizzes_path, notice: "Quiz was successfully created." }
        format.json { render :show, status: :created, location: @quiz }
      else
        @quizzes = Quiz.all.order(created_at: :desc)
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@quiz, partial: 'quizzes/form', locals: { quiz: @quiz }) }
        format.html { render :index, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quizzes/1 or /quizzes/1.json
  def update
    respond_to do |format|
      if @quiz.update(quiz_params)
        format.html { redirect_to @quiz, notice: "Quiz was successfully updated." }
        format.json { render :show, status: :ok, location: @quiz }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @quiz.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /quizzes/1 or /quizzes/1.json
  def destroy
    @quiz.destroy
    respond_to do |format|
      format.html { redirect_to quizzes_url, notice: "Quiz was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def reset
    @quiz = Quiz.find(params[:id])
    @questions = @quiz.questions
    @questions.each do |question| 
      question.mark_as_unanswered
    end
    @number_correct = 0
  end

  def build
    @question = @quiz.questions.new
  end

  def complete
    @percentage_correct =  @correct_answer_count.to_f / @number_of_questions_in_quiz
  end

  def session_maker
  
    unless @question.present?
      redirect_to complete_path
    end

  end

  def add_question_to_quiz
    @quiz = Quiz.find(params[:id])
    @question = @quiz.questions.new
 
  end

  def receive_question
    @question = @quiz.questions.new(questions_params)
  
    @question.answer = params[:answer]

    if @question.save
      format.html { redirect_to quiz_path(@quiz), notice: "Question was successfully created under #{@quiz.name}"}  
    else
      format.html {redirect_to quiz_path(@quiz), notice: "Question was not saved." }
     
    end
  end

  def handle_answer
    @attempted_answer = params[:attempted_answer].downcase
    @attempted_answer = @attempted_answer.downcase
    @correct_answer = @question.answer
    @correct_answer = @correct_answer.downcase

    if @attempted_answer == @correct_answer
      right_answer = AttemptedAnswer.new(question_id: @question.id, attempted_answer: @attempted_answer, correct_answer: @correct_answer)
      right_answer.save!
      @correct_answer_count += 1
      @questions.shift

      if @questions.count == 0
        respond_to do |format|
          format.html { redirect_to complete_path, notice: "Correct! "}
        end
        
      else
        session[:questions] = @questions 
    
        respond_to do |format|
          format.html { redirect_to session_maker_path(@quiz), notice: "Correct! "}
        end
      end
    else
      wrong_answer = AttemptedAnswer.new(question_id: @question.id, attempted_answer: @attempted_answer, correct_answer: @correct_answer)
      wrong_answer.save!
      @questions.shift
      if @questions.count == 0
        respond_to do |format|
          format.html { redirect_to complete_path, notice: "Wrong! "}
          format.json { render :complete, status: :ok, location: @quiz }
        end  
      else
        session[:questions] = @questions 
        respond_to do |format|
          format.html { redirect_to session_maker_path(@quiz), notice: "Wrong!"}
          format.json { render json: @question.errors, status: :unprocessable_entity }
        end
      end
    end

  end

  def pick_random_quiz
    @random_quiz = Quiz.all.sample
    redirect_to quiz_path(@random_quiz)
  end

  private
    def setup_quiz
      @quiz ||= Quiz.find(params[:id])
      @questions ||= session[:questions]
    
      if @questions.present?  
        @question = Question.find(@questions[0]["id"])
      else
        @questions = @quiz.questions.to_a 
        @question = @questions.first
      end
      @correct_answer_count ||= 0
      @number_of_questions_in_quiz  ||= 0
    end

    def set_questions
      @questions = Question.where(quiz_id: @quiz.id)
    end

    def set_number_correct
      if !@number_correct.present?
        @number_correct = 0
      end
    end

    def calculate_score
      @total_questions = @quiz.questions.count
      @percentage_correct = @number_correct / @total_questions
    end

    def quiz_params
      params.require(:quiz).permit(:name, :difficulty, :quiz_id)
    end

    def intro_new_quiz(questions)
      questions.each do |question|
          question.mark_as_unanswered
      end
  end
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/_add_question_to_quiz.html.erb
<br>
<%= form_with(model: @question, local: true) do |form| %>
    <% if @question.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
  
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :answer %>
      <%= form.text_field :answer %>
    </div>
    <div class="field">
      <%= form.label :quiz_id %>
      <%= form.text_field :quiz_id %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/quizzes/_all_questions_answered.html.erb
Nice work! Your score is:
<%= 14 %>
<br>
Click here to reset the quiz:
<br>
<%= link_to "Reset", reset_path %>
<br>
<%= link_to 'Home', root_path  %>

app/views/quizzes/_answer_form.html.erb
<%= form_with(model: question, local: true, method: :post, ) do |form| %>
  <% if question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
        <% question.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= form.text_field :attempt %>
  </div>

  <div class="actions">
    <%= form.submit "Submit Answer" %>
  </div>
<% end %>

app/views/quizzes/_form.html.erb
<%= form_with(model: quiz, local: true) do |form| %>
  <% if quiz.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(quiz.errors.count, "error") %> prohibited this quiz from being saved:</h2>

      <ul>
        <% quiz.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :difficulty %>
    <%= form.text_field :difficulty %>
  </div>

  <div class="actions white-submit-button">
    <%= form.submit class: ""%>
  </div>
<% end %>

app/views/quizzes/_quiz.html.erb
<div id="<%= dom_id quiz %>" class="rounded-box" style="margin: 30px;">

  <tr>
    <strong><%= link_to quiz.name, quiz %></strong>
    <br>
    <hr>
   
    <td><%= link_to "Edit", edit_quiz_path(quiz) %></td>
    <td><%= link_to "Destroy", quiz, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    <br>
    <td><%= link_to "Take Quiz", session_maker_path(quiz) %></td>
  </tr>


</div>

app/views/quizzes/add_question_to_quiz.html.erb
Add a question to quiz!
Quiz: <%= @quiz.name %>

Add a form here:
<br>
<%= form_with(model: @question, local: true) do |form| %>
    <% if @question.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>
  
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="field">
      <%= form.label :title %>
      <%= form.text_field :title %>
    </div>
  
    <div class="field">
      <%= form.label :answer %>
      <%= form.text_field :answer %>
    </div>
    <div class="field">
      <%= form.label :quiz_id %>
      <%= form.text_field :quiz_id %>
    </div>
    <div class="actions">
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/quizzes/build.html.erb
<%= turbo_stream_from :questions %>

<%= turbo_frame_tag :question_form do %>
  <%= render 'add_question_to_quiz', question: @question %>
<% end %>
<%= link_to "Take this quiz", session_maker_path(@quiz) %>

<%= turbo_frame_tag :questions do %>
  <%= render @question %>
<% end %>

app/views/quizzes/categories.html.erb
#Create sortable list
#Gather all the categories
# For each category, list the quizzes it has
# each category has a box

<% @categories.each do |category| %>
    <div class="button-link">
        <%= link_to category.name, category %>
        <%= category.quantity %>
    <div>
<% end %>

app/views/quizzes/complete.html.erb
<% if @quiz.questions.count > 0 %>

All done! Your score is:
<%= @correct_answer_count %>
<br>
Percentage Correct:
<%= @percentage_correct %>
<br>
Click here to reset the quiz:
<br>
<%= link_to "Reset", reset_path %>
<br>

<%= link_to 'Home', root_path(@quiz)  %>

<% else %>
This quiz doesn't have any questions yet! 
    <%= link_to "Add questions", build_quiz_path(@quiz) %>
    <%= link_to 'Home', root_path(@quiz)  %>
<% end %>   

app/views/quizzes/edit.html.erb
<h1>Editing Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Show', @quiz %> |
<%= link_to 'Back', quizzes_path %>

app/views/quizzes/index.html.erb
<%= turbo_stream_from :quizzes %>


<div class="split left">
  <div class="centered">
  <h1>Add a Quiz</h1>
    <%= turbo_frame_tag :quiz_form do %>
      <%= render 'quizzes/form', quiz: @quiz %>
    <% end %>
  </div>
</div>

<div class="split right">
  <div class="centered">
  <h1>Quizzes</h1>
    <%= turbo_frame_tag :quizzes do %>
      <%= render @quizzes %>
    <% end %>
  </div>
</div>

app/views/quizzes/new.html.erb
<h1>New Quiz</h1>

<%= render 'form', quiz: @quiz %>

<%= link_to 'Back', quizzes_path, class: "reg-button" %>

app/views/quizzes/session.html.erb
<h1>Currently in a session</h1>

<%= @question.title %>

app/views/quizzes/show.html.erb
Quiz Name: <%= @quiz.name %>
<hr>
<div>
  <%= link_to "Edit this quiz", edit_quiz_path(@quiz) %> |
  <%= link_to "Back to quizzes", quizzes_path %>
  <%= link_to "Destroy this quiz", @quiz, method: :delete %>
  <%= link_to "Build Quiz", build_quiz_path(@quiz) %>
</div>
<hr>
Here are all the questions that will be on the quiz:

<% @quiz.questions.each do |question| %>
  <h2>Question:</h2>
  <%= question.title %>
  <br>
  Answer:<%= question.answer %>
  <hr>
  <br>
<% end %>